#!/usr/bin/env python3
import colors as c
from random import randint

def pick():
    return randint(1,4)
    

if __name__ == '__main__':
print("welcome to simon")
num = pick()
print(num)


def pick_colored():
    num = pick()
    if num == 1:
        return c.red + 1:
    elif num == 2: 
        return c.blue + '2'
    elif num == 3: 
        return c.yellow + 3
