#!/usr/bin/env python3
import colors as c
from random import randint
import time as t
def pick():
    return randint(1,4)
nums = []

def pick_colored():
    num = pick()
    if num == 1:
        return c.red + 1
    elif num == 2: 
        return c.blue + '2'
    elif num == 3: 
        return c.yellow + 3
    elif num == 4:
        return c.green + 4
if __name__ == '__main__':
    input('(press enter to begin)')
    while True:
        new = pick()
        nums.append(new)
        print(nums)
        t.sleep(1)
        print(c.clear)
        order = input("simon says type the numbers: ")
        answer = []
        for n in order:
            answer.append int(n))
            if answer == numbers:
                print(:oooooooooooohhhhhhhhhhhh ohoohohohoohhhhoooooohhhhhhh")
                else:
                print("sad airhorns")


